### ISSUE TITLE
Wisconsin County Trunk Highway shields

### ISSUE THREAD

**Issue by skylerbunny** [kennykb/osm-shields#12]
Wisconsin has approximately 350 relations (this number continues to grow) which should all use the same shield pattern, for County Trunk Highways. Each county maintains its own system, and thus the networks are distinct, but the signs they use are consistent across the state. A general specification for the shield follows the list.

The following 72 county names are potentially used in the third field of a `network` tag, when prefixed with `US:WI:`
Adams
Ashland
Barron
Bayfield
Brown
Buffalo
Burnett
Calumet
Chippewa
Clark
Columbia
Crawford
Dane
Dodge
Door
Douglas
Dunn
Eau Claire
Florence
Fond du Lac
Forest
Grant
Green
Green Lake
Iowa
Iron
Jackson
Jefferson
Juneau
Kenosha
Kewaunee
La Crosse
Lafayette
Langlade
Lincoln
Manitowoc
Marathon
Marinette
Marquette
Menominee
Milwaukee
Monroe
Oconto
Oneida
Outagamie
Ozaukee
Pepin
Pierce
Polk
Portage
Price
Racine
Richland
Rock
Rusk
Saint Croix
Sauk
Sawyer
Shawano
Sheboygan
Taylor
Trempealeau
Vernon
Vilas
Walworth
Washburn
Washington
Waukesha
Waupaca
Waushara
Winnebago
Wood

Shields for this system uses marker M1-5A, which is outlined here: https://wisconsindot.gov/dtsdManuals/traffic-ops/manuals-and-standards/signplate/mseries/M1-5a.pdf

**Comment by skylerbunny** [comment]
The first part of this feature request could simply tie together the relations and use a generic identical square bordered shield for the 72 networks. The 'COUNTY' shields unique to Wisconsin would just have to be done when there's time.

**Comment by kennykb** [comment]
OK, the missing counties are there now. If anyone tags them, they'll show up.
